# Generated by Django 3.2.14 on 2022-07-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('classes', models.IntegerField(choices=[('Spinning', 'Spinning'), ('Ride_that_hill', 'Ride_that_hill'), ('LadyBike', 'LadyBike')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('Fully_Booked', 'Fully_Booked'), ('Availble', 'Availble')])),
                ('seats', models.IntegerField(default=True)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('class_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='booking.classname')),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('sessiondate', models.DateField()),
                ('bookingstatus', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('p', 'Pending')], default='p', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.session')),
            ],
        ),
    ]
