# Generated by Django 3.2.14 on 2022-08-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='requested_time',
        ),
    ]
