# Generated by Django 3.2.14 on 2022-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classes',
            field=models.IntegerField(choices=[('Spinning', 'Spinning'), ('Ride_that_hill', 'Ride_that_hill'), ('LadyBike', 'LadyBike')], primary_key=True, serialize=False),
        ),
    ]
