# Generated by Django 3.2.14 on 2022-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_classname_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Fully_Booked', 'Fully_Booked'), ('Availble', 'Availble')], default='Available', max_length=15),
        ),
    ]
