# Generated by Django 3.2.14 on 2022-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_classname_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classes',
            field=models.IntegerField(choices=[('Spinning', 1), ('Ride_that_hill', 2), ('LadyBike', 3)], primary_key=True, serialize=False),
        ),
    ]
