# Generated by Django 3.2.14 on 2022-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_classname_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classes',
            field=models.IntegerField(choices=[(1, 'Spinning'), (2, 'Ride_that_hill'), (3, 'LadyBike')], primary_key=True, serialize=False),
        ),
    ]
