# Generated by Django 3.2.14 on 2022-08-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classes',
            field=models.CharField(choices=[('Spinning', 'Spinning'), ('Ride_that_hill', 'Ride_that_hill'), ('LadyBike', 'LadyBike')], max_length=15, primary_key=True, serialize=False),
        ),
    ]
